POST http://localhost:3000/users/register HTTP/1.1
Accept: : application/json
Content-Type: application/json

{
     "email": "admin2@email.com", "name": "admin", "password": "Rc123456!", "isAdmin": false 
}

###
POST http://localhost:3000/users/register HTTP/1.1
Accept: : application/json
Content-Type: application/json

{
     "email": "admin1@email.com", "name": "admin", "password": "Rc123456!", "isAdmin": true 
}
###FOR ADMIN
POST http://localhost:3000/users/login HTTP/1.1
Accept: : application/json
Content-Type: application/json

{
    "email":"admin2@email.com" ,"password":"Rc123456!"
}
###
POST http://localhost:3000/users/tokenValidate 
Accept: : application/json
Content-Type: application/json
//send the token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluMUBlbWFpbC5jb20iLCJpYXQiOjE2Mzg0NDMyNDYsImV4cCI6MTYzODQ0Mzg0Nn0.FlYdOObn5Se961MXxa7T-P0M4v7_JeBIkNMXLt9WH-Y
###
GET  http://localhost:3000/api/v1/information HTTP/1.1
Accept: : application/json
Content-Type: application/json

###
POST http://localhost:3000/users/token HTTP/1.1
Accept: : application/json
Content-Type: application/json

//send the refresh token
{
    "token": "pd6YiR2LWvAurW15A5LokTopg067EbilfJSZ6QLc5jxWrvUPq76Oz5zvuQ4mJGnnZ4KE4iN6CYfuifs0htKRmUVJ7XHhoHYJIh6f6yVeOuqrPMfZCszJQP6zvTGjfBar0QoLdIj118nH8fhTQ5ehlntLURq9A1Eb2llA5n3uvKjyk48W4uWyWK0Nr3o0mCnw0yMFfL3mriqemIJD4D16mAisLzVlsQTxMXztd4dBxy9fc9MG4OfxXLa7YXmSYPg2"
}
###

POST http://localhost:3000/users/logout HTTP/1.1
Accept: : application/json
Content-Type: application/json

{
    "token": "pd6YiR2LWvAurW15A5LokTopg067EbilfJSZ6QLc5jxWrvUPq76Oz5zvuQ4mJGnnZ4KE4iN6CYfuifs0htKRmUVJ7XHhoHYJIh6f6yVeOuqrPMfZCszJQP6zvTGjfBar0QoLdIj118nH8fhTQ5ehlntLURq9A1Eb2llA5n3uvKjyk48W4uWyWK0Nr3o0mCnw0yMFfL3mriqemIJD4D16mAisLzVlsQTxMXztd4dBxy9fc9MG4OfxXLa7YXmSYPg2"
}
###
GET  http://localhost:3000/api/v1/information HTTP/1.1

###

GET http://localhost:3000/api/v1/users HTTP/1.1
Accept: : application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluMkBlbWFpbC5jb20iLCJpYXQiOjE2Mzg0NTA1NjMsImV4cCI6MTYzODQ1MTE2M30.ka4KUOC_5YeyAipnSafQfrjSN5NMLuWvyY16n173eQY
###Access token(only admin)

OPTIONS  http://localhost:3000/ HTTP/1.1
Accept: : application/json
Content-Type: application/json
###
GET http://localhost:3000/api/v1/refreshTokens HTTP/1.1
Accept: : application/json
Content-Type: application/json
